# hexo-theme-mellow
# https://github.com/yscoder/hexo-theme-indigo
# ä¸ºäº†é¿å…æœªçŸ¥è§£æé”™è¯¯ï¼Œé…ç½®ä¸­çš„ç¼©ç´§ä¸º2ä¸ªåŠè§’ç©ºæ ¼ï¼Œå†’å·åè·Ÿ1ä¸ªåŠè§’ç©ºæ ¼
# ä¸éœ€è¦çš„é…ç½®å¯ä»¥æ³¨é‡Šæ‰ï¼Œä¹Ÿå¯ä»¥ä¿®æ”¹å¯¹åº”é”®å¸ƒå°”å€¼(enableå’Œdisable)


#####################
####   å…¨å±€é…ç½®    ###
#####################

# æ˜¯å¦å¯ç”¨lesså‹ç¼©
## å»ºè®®å‹ç¼©ï¼Œå¹¶ä¸”ä¸è¦ä¿®æ”¹é»˜è®¤paths
less:
  compress: true #æ˜¯å¦å‹ç¼©
  paths:
    - source/css/style.less #å‹ç¼©åçš„æ–‡ä»¶è·¯å¾„

# ç«™ç‚¹icoå›¾æ ‡
favicon: /img/favicon.ico

# å¤´éƒ¨èƒŒæ™¯
# å¦‚/img/banner.jpg æˆ– https://i.loli.net/2017/12/12/5a2fd18a74471.jpg
headerBg: /img/banner.jpg

# åŠ¨æ€å®šä¹‰title
title_change:
  normal: å—¨~ğŸ‘‹     #é¡µé¢è·å¾—ç„¦ç‚¹æ—¶æ˜¾ç¤º(çŸ­æš‚å­˜åœ¨)
  leave: çœ‹è¿™é‡Œ~çœ‹è¿™é‡Œ~          #é¡µé¢å¤±å»ç„¦ç‚¹åæ˜¾ç¤º

# è§„èŒƒç½‘å€
## è®©æœç´¢å¼•æ“é‡å®šå‘ä½ çš„ä¸åŒåŸŸåã€ä¸åŒå­åŸŸã€åŒåŸŸä¸åŒç›®å½•çš„ç«™ç‚¹åˆ°ä½ æœŸæœ›çš„è·¯å¾„
## https://support.google.com/webmasters/answer/139066
## å‡è®¾é…ç½®ä¸º canonical: http://www.lujingtao.comï¼Œé‚£ä¹ˆä»æœç´¢å¼•æ“ä¸­ www.lujingtao.com è¿›å…¥ä¼šé‡å®šå‘åˆ° lujingtao.com
canonical: false

# DaoVoice èŠå¤©å®¤
daovoice:
  app_id: 

# ä¸»é¡µæ–‡ç« æ’åºæ–¹å¼
## true æŒ‰ç…§æ–‡ç« æ›´æ–°æ—¶é—´æ’åº
## false æŒ‰ç…§æ–‡ç« åˆ›å»ºæ—¶é—´æ’åº
articleSort: false

# ç«™æµè§ˆæ•°ç»Ÿè®¡
visit_counter: 
  site_uv: true # è®¿å®¢æ•°é‡
  site_pv: true # æµè§ˆæ¬¡æ•°

##############################################################################################################################

#####################
####   èœå•é…ç½®    ###
#####################

# å¤´åƒ
avatar: /img/avatar.jpg

# å¤´åƒç‚¹å‡»åçš„é“¾æ¥åœ°å€
avatar_link: / #é»˜è®¤ä¸ºä¸»é¡µ

# å¤´åƒåŒºåŸŸèƒŒæ™¯å›¾
brand: /img/brand.jpg

# ç”µå­é‚®ä»¶
email: å¿ƒä¸­æœ‰å…‰ï¼Œå¿½æ˜å¿½æš—ã€‚

# ç”µå­é‚®ä»¶ä¸‹æ–¹çš„é“¾æ¥å›¾æ ‡
## æ–°è¿æ¥è§„åˆ™[name]: url | icon
## ä½¿ç”¨fontawesomeå›¾æ ‡ï¼Œåªéœ€è¦å†™å›¾æ ‡åã€‚github -> icon-github | fa-github
## http://http://fontawesome.dashgame.com/
menu_link: 
  QQ: http://shang.qq.com/email/stop/email_stop.html?qq=1518801557 | qq
  github: https://github.com/YuanLiChenAi | github
  weibo: https://weibo.com/5653458750/ | weibo
  music: http://music.163.com/#/user/home?id=583505936 | music

# æ·»åŠ æ–°èœå•é¡¹éµå¾ªä»¥ä¸‹è§„åˆ™
## menu:
##  link:               [å¿…è¦][ä¸æ¸²æŸ“] ç”¨äºåŒºåˆ†ç±»åˆ«
##    icon: _blank      [å¿…è¦][æ¸²æŸ“] èœå•å›¾æ ‡ã€‚ä½¿ç”¨å†…ç½®fontawesomeå›¾æ ‡ï¼Œçœç•¥å‰ç¼€
##    text: About       [å¿…è¦][æ¸²æŸ“] èœå•æ–‡å­—ä¿¡æ¯
##    url: /about       [å¿…è¦][æ¸²æŸ“] èœå•é“¾æ¥ï¼Œç»å¯¹æˆ–ç›¸å¯¹è·¯å¾„ã€‚
##    target: _blank    [å¿…è¦][ä¸æ¸²æŸ“] æ˜¯å¦è·³å‡ºï¼Œçœç•¥åˆ™åœ¨å½“å‰é¡µé¢æ‰“å¼€
menu:
  home:
    text: ä¸»é¡µ
    url: /
    icon: home
  flag:
    text: CTF
    url: https://ctf.yuanlichenai.cn/
    icon: flag
  th-list:
    text: åˆ†ç±»
    url: /categories
    icon: th-list
  tags:
    text: æ ‡ç­¾
    url: /tags
    icon: tags
  archives:
    text: å½’æ¡£
    url: /archives
    icon: archives
  test:
    text: æµ‹è¯•
    url: /test
    icon: bug
  study:
    text: å¯¼èˆª
    url: /study
    icon: plane
  link:
    text: å‹é“¾
    url: /links
    icon: link
  about:
    text: å…³äº
    url: /about
    icon: user

# è¿›å…¥æ–‡ç« æ—¶è‡ªåŠ¨éšè—
auto_hide: false

##############################################################################################################################

#####################
####   é¦–é¡µé…ç½®    ###
#####################

# é¦–é¡µæ˜¯å¦å¼€å¯ç½®é¡¶æ ‡å¿—
top_icon: true

# é¦–é¡µä¸­æ–‡ç« ç¼©ç•¥å›¾æ˜¯å¦ä½¿ç”¨ç›¸å¯¹è·¯å¾„
## åªæœ‰disableä¸ºtrueçš„æ—¶å€™ï¼Œä¸‹é¢çš„è·¯å¾„urlæ‰ä¼šç”Ÿæ•ˆï¼Œè·¯å¾„åœ°å€ä½äº: å…¨å±€/source/uploads
## uploadså¯ä»¥æ˜¯ä»»æ„å­˜åœ¨æ–‡ä»¶å¤¹å(ä¸å­˜åœ¨å¯ä»¥è‡ªå·±é—¯å°†)ï¼Œç”¨äºæ”¾ç½®å„ç§éœ€è¦å¼•å…¥åˆ°é¡µé¢çš„é™æ€æ–‡ä»¶ï¼Œå¦‚imgç­‰ã€‚
## å‚è€ƒhttps://hexo.io/zh-cn/docs/asset-folders.html#æ–‡ç« èµ„æºæ–‡ä»¶å¤¹


##############################################################################################################################

#####################
####   æ–‡ç« é…ç½®    ###
#####################

# é¡µé¢æ ‡é¢˜
## æ ‡ç­¾é¡µ / åˆ†ç±»é¡µ / å½’æ¡£é¡µçš„æ ‡é¢˜åªèƒ½åœ¨è¿™é‡Œè®¾ç½®
## å…¶ä»–è‡ªå®šä¹‰é¡µé¢æ ‡é¢˜åœ¨é¡µé¢markdownæ–‡ä»¶çš„titleä¸­è®¾ç½®
tags_title: æ ‡ç­¾              #æ ‡ç­¾é¡µ
categories_title: åˆ†ç±»  #åˆ†ç±»é¡µ
archives_title: å½’æ¡£      #å½’æ¡£é¡µ

# ä¸»é¡µæ–‡ç« æ‘˜è¦ç¼©ç•¥å›¾
defaultthumb: false

# è‡ªåŠ¨ç”Ÿæˆæ–‡ç« æ‘˜è¦
## æ˜¾ç¤ºåœ¨ä¸»é¡µä¸­
## excerpt_lengthåªåœ¨excerpt_renderä¸ºtrueæ—¶ç”Ÿæ•ˆã€‚
## excerpt_renderä¸ºfalseæ—¶å¯è¿›è¡Œæ‰‹åŠ¨æˆªæ–­ã€‚æ–¹æ³•ä¸ºåœ¨æ–‡ç« çš„markdownæ–‡ä»¶ä¸­åŠ å…¥<!--more-->ï¼Œå…¶ä¹‹å‰çš„å†…å®¹è§†ä¸ºæ‘˜è¦éƒ¨åˆ†ã€‚
excerpt_render: false   #è‡ªåŠ¨æˆªæ–­
excerpt_length: 200     #æˆªæ–­é•¿åº¦
excerpt_link: more      #æ›´å¤šæŒ‰é’®å†…å®¹

# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æœ€åæ›´æ–°æ—¶é—´
## ä½äºæ–‡ç« åº•éƒ¨çš„copyright
show_last_updated: true

# ç‰ˆæƒä¿¡æ¯copyright
## ä½äºæ–‡ç« åº•éƒ¨
## hexoä¸­æ‰€æœ‰å˜é‡åŠè¾…åŠ©å‡½æ•°ç­‰å‡å¯è°ƒç”¨ï¼Œå…·ä½“è¯·æŸ¥é˜… hexo.io
postMessage: è½¬è½½æ³¨æ˜å‡ºå¤„ï¼ŒåŸæ–‡åœ°å€ï¼š<a href="<%- url_for(page.path).replace(/index\.html$/, "") %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, "") %></a>

# æ‰“èµ
## å¯ä»¥åœ¨æ–‡ç« markdownä¸­è®¾ç½®reward: falseæ¥å–æ¶ˆæœ¬ç¯‡æ–‡ç« çš„æ‰“èµåŠŸèƒ½
## å…¨å±€å–æ¶ˆç›´æ¥æ³¨é‡Šä¸‹æ–¹é…ç½®
reward:
  title: æˆ‘ä»¬ä¸€èµ·æ¥è®©è¿™ä¸ªä¸–ç•Œæœ‰è¶£ä¸€ç‚¹
  wechat: /img/reward-wechat.jpg     #å¾®ä¿¡
  alipay: /img/reward-alipay.jpg     #æ”¯ä»˜å®

# åˆ†äº«
## å†…ç½®6ç§åˆ†äº«é€”å¾„ï¼Œä¸éœ€è¦çš„è®¾ç½®å¯¹åº”çš„ä¸ºfalse
## å¯ä»¥åœ¨æ–‡ç« markdownä¸­è®¾ç½®share: falseæ¥å–æ¶ˆæœ¬ç¯‡æ–‡ç« çš„æ‰“èµåŠŸèƒ½
## å…¨å±€å–æ¶ˆç›´æ¥æ³¨é‡Šä¸‹æ–¹é…ç½®
share_items:
  weibo: true
  wechat: true
  qq: true
  facebook: false
  twitter: false
  google: false

# ç›®å½•
## æ•æ‰æ–‡ç« markdownçš„#ä¸€çº§æ ‡é¢˜ / ##äºŒçº§æ ‡é¢˜ / ###ä¸‰çº§æ ‡é¢˜ç­‰
## ä½äºæ–‡ç« å³ä¾§ï¼Œç§»åŠ¨ç«¯æˆ–è€…å°å±å¹•è‡ªåŠ¨éšè—
toc:
  enable: true
  list_number: true  # æ˜¯å¦æ˜¾ç¤ºæ•°å­—æ’åº

##############################################################################################################################

#####################
####   é¡µè„šé…ç½®    ###
#####################

# å›ºå®šé¡µè„š
footer_fixation: false

# å‹æƒ…é“¾æ¥
blogroll:
  # item1:
  #   name: HOME
  #   url: https://www.lujingtao.com
  #item2:
    #name: gitee
    #url: https://www.gitee.com
  #item3:
    #name: coding
    #url: https://www.coding.net

# ç‰ˆæƒèµ·å§‹å¹´ä»½
since_year: 2017

# icpå¤‡æ¡ˆå·
## ä¾‹å¦‚ICP_license: äº¬ICPå¤‡123456å·
ICP_license: false

# é©±åŠ¨å¼•æ“/ä¸»é¢˜ç­‰ä¿¡æ¯
power: true

# æ­è½½æœåŠ¡å™¨ä¿¡æ¯
## å¦‚æœä½¿ç”¨githubæˆ–è€…giteeç­‰pagesåŠŸèƒ½ï¼Œå¯ä»¥è®¾ç½®ä¸ºfalse
## å¦‚æœä½¿ç”¨coding.netçš„pagesä½œä¸ºhostï¼Œè¯¥é€‰é¡¹å°†å¸®åŠ©æ‚¨æ¸…æ¥šé»˜è®¤å¹¿å‘Šé¡µé¢
## è¯¦æƒ…è§https://coding.net/help/doc/pages/guide-page.html
hosted: false

##############################################################################################################################

#####################
####   ç¬¬ä¸‰æ–¹é…ç½®   ###
#####################

# æœç´¢
local_search: true

# ç™¾åº¦ç»Ÿè®¡
baidu_tongji: #appid

# gitmentè¯„è®ºç³»ç»Ÿ
## https://github.com/imsun/gitment
gitment:
  enable: true
  lazy: true #æ˜¯å¦å¼€å¯åˆå§‹åŒ–éšè—è¯„è®º
  owner: YuanLiChenAi #githubè´¦å·
  repo: blog #ç•™è¨€ä»“åº“
  oauth: 
    client_id: 59f005779b1a5d300083 #client_id
    client_secret: 78d6b45816143073b16a95e1ffb4b0449bd47650  #client_id
  perPage: 10 #åˆ†é¡µ

# valineè¯„è®ºç³»ç»Ÿ
## https://valine.js.org/
valine:
  enable: false
  appid: #appid
  appkey: #appkey
  notify: true  #æ˜¯å¦å¼€å¯é‚®ç®±æé†’
  verify: true  #æ˜¯å¦å¼€å¯éªŒè¯ç 
  placeholder: give me some sugers plz... #ç•™è¨€æ¿ä¸­çš„é¢„ç•™ä¿¡æ¯
  avatar: 'wavatar'  #ç”¨æˆ·å¤´åƒ

# æ–‡ç« æµè§ˆç»Ÿè®¡
leancloud_visitors:
  enable: false
  app_id: #appid
  app_key: #appkey
  icon: true #trueåªæ˜¾ç¤ºå›¾æ ‡ï¼Œfalseåªæ˜¾ç¤ºæ–‡å­—

# æ•°å­¦å…¬å¼
mathjax:
  enable: true
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

# æ˜¯å¦ä½¿ç”¨æŒ‰é’®wavesæ’ä»¶
waves: true